version: '3.8'

services:
  privmatch-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    networks:
      - privmatch-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - privmatch-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./privmatch.com_ssl_certificate.cer:/etc/nginx/ssl/privmatch.com_ssl_certificate.cer
      - ./_.privmatch.com_private_key.key:/etc/nginx/ssl/_.privmatch.com_private_key.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - privmatch-network
    depends_on:
      - privmatch-api

volumes:
  mysql-data:

networks:
  privmatch-network:
    driver: bridge
